config/routes.rb
Florarails::Application.routes.draw do
  get "catalogo/procurar"
  match 'catalogo/:id/detalhes' => 'catalogo#detalhes', :as => :detalhes
  match 'catalogo/:id/procurar' => 'catalogo#procurar', :as => :procurar
  match 'catalogo/:id/adicionar_no_carrinho' => 'catalogo#adicionar_no_carrinho', :as => :adicionar_no_carrinho
  match 'catalogo/:id/lista_itens_grupo(/:id)' => 'catalogo#lista_itens_grupo', :as => :lista_itens_grupo

  resources :produtos

  get "grupos/index"

  resources :grupos
  resources :catalogo
  resources :clientes
  match 'clientes/buscar_cep' => 'clientes#buscar_cep', :as => :buscar_cep
  
end

app/models/produto.rb
# encoding: utf-8
# O comentário acima é para aceitar caracteres com acento
class Produto < ActiveRecord::Base
  attr_accessible :descricao, :preco, :titulo, :validade, :imagem, :grupo_id
  
  belongs_to :grupo
  
  def self.localizar_produto_para_venda
    #find(:all, :order => "titulo",:conditions => ['validade >= ?', Date.current])
    find(:all, :order => "titulo")
  end

  def self.lista_produto_grupo(grupo)
     find(:all, :order => "titulo",
        :conditions => ['validade >= ? and grupo_id = ?', Date.current, grupo])
  end
  
  def to_param
    require 'iconv'
    texto = Iconv.iconv("ASCII//IGNORE//TRANSLIT","UTF-8",titulo).join.gsub(/[\s]+/i,
    '_').gsub(/[^a-z0-9\_]+/i,'').downcase
    "#{id}-#{titulo}"
  end
  
  #Configurações do PaperClip
  has_attached_file :imagem,
  :styles => {:grande => "800x600>",
              :media => "200x150>",
              :pequena => "80x60>",
              :thumb => "40x30>"},
  :path => "public/system/:class/:id/:filename",
  :url => "/system/:class/:id/:basename.:extension",
  :default_url => "/system/imagens/semfoto.jpg"
  #Nos parâmetros path e URL estamos definindo que as imagens estarão 
  #no diretório app/assets/images
  #e que será criado um diretório como o nome da classe (no nosso
  #exemplo produtos) e o respectivo id.
  #Já o default_url irá definir uma imagem que será exibida por default
  #caso ela seja apagada, por exemplo.
  validates_attachment_presence :imagem,
  :message => 'Imagem deve ser informada'
  validates_attachment_content_type :imagem,
  :content_type => ['image/jpeg', 'image/png','image/gif','image/pjpeg'],
  :message => 'Tipo da imagem inválido'
  #Validações do Modelo
  validates_presence_of :titulo, :descricao
  validates_numericality_of :preco
  validate :preco_deve_ser_no_minimo_um_centavo
  validates_uniqueness_of :titulo
  #Método protected indica que o acesso é apenas a objetos da
  #classe e subclasses
  
  protected
  def preco_deve_ser_no_minimo_um_centavo
    errors.add(:preco, 'deve ser no mínimo 0.01') if preco.nil? || preco < 0.01
  end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @produtos }
    end
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
    @produto = Produto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @produto }
    end
  end

  # GET /produtos/new
  # GET /produtos/new.json
  def new
    @produto = Produto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @produto }
    end
  end

  # GET /produtos/1/edit
  def edit
    @produto = Produto.find(params[:id])
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(params[:produto])

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render json: @produto, status: :created, location: @produto }
      else
        format.html { render action: "new" }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /produtos/1
  # PUT /produtos/1.json
  def update
    @produto = Produto.find(params[:id])

    respond_to do |format|
      if @produto.update_attributes(params[:produto])
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto = Produto.find(params[:id])
    @produto.destroy

    respond_to do |format|
      format.html { redirect_to produtos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_for(@produto) do |f| %>
  <% if @produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% @produto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br />
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </div>
  <div class="field">
    <%= f.label :preco %><br />
    <%= f.text_field :preco %>
  </div>
  <div class="field">
    <%= f.label :validade %><br />
    <%= f.date_select :validade %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/produtos/_formproduto.html.erb
<%= form_for(@produto, :html => {:multipart => true}) do |form| %>
    <%= form.error_messages %>
    <p>
       <%= form.label :titulo, "Título" %></br>
       <%= form.text_field :titulo, :size => 40 %></p>

    <p>
       <%= form.label :descricao, "Descrição" %></br>
       <%= form.text_area :descricao, :rows => 6,
       :cols => 40 %></p>

	<p>
       <%= form.label :preco, "Valor" %></br>
       <%= form.text_field :preco, :size => 12 %></p>

	<p>
       <%= form.label :validade, "Data de validade" %></br>
       <%= form.date_select(:validade,
       :order => [:day, :month, :year],
       :use_month_numbers => true) %></p>

   	<p>
       <%= form.label :imagem %></br>
       <%= form.file_field :imagem %></p>

	<p>
       <%= form.label :grupo, "Grupo" %></br>
       <%= form.select :grupo_id, 
           Grupo.find(:all).collect {|gru| [gru.descricao,gru.id]} %></p>

    <%= form.submit "Gravar" %>

</fieldset>
<% end %>

app/views/produtos/edit.html.erb
<fieldset>
    <legend>Edição de Produtos</legend>
    <%=render 'formproduto'%>

app/views/produtos/index.html.erb
<h1>Listagem dos Produtos</h1>

<table>
  <tr>
    <th>Título</th>
    <th>Imagem</th>
    <th>Descrição</th>
    <th>Preço</th>
    <th>Validade</th>
  </tr>

<% @produtos.each do |produto| %>
  <tr>
    <td><%=h produto.titulo %></td>
    <td><%= image_tag produto.imagem.url(:pequena) %></td>
    <td><%=h truncate(produto.descricao, :ommision => "...", :length => 35) %></td>
    <td><%= numero_em_reais(produto.preco) %></td>
    <td><%=h produto.validade.strftime("%d/%m/%Y") %></td>
    <td><%= link_to image_tag("pencil_go.png"), produto %>
    <%= link_to image_tag("pencil.png"), edit_produto_path(produto) %>
    <%= link_to image_tag("pencil_delete.png"), produto, method: :delete, data: { confirm: 'Você tem certeza que deseja apagar o produto?' } %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to image_tag("pencil_add.png"), new_produto_path %>
<%= link_to 'Novo produto', new_produto_path %>

app/views/produtos/new.html.erb
<fieldset>
    <legend>Inclusão de Produtos</legend>
    <%=render 'formproduto'%>

app/views/produtos/show.html.erb
<h2>Detalhes do produto <%= @produto.titulo %></h2>
<h4>
<p>Código: <%= @produto.id %></p>
<p>Descrição: <%=h @produto.descricao %></p>
<p>Imagem: <%= image_tag @produto.imagem.url(:thumb) %></p>
<p>Valor: <%=h @produto.preco %></p>
<p>Validade: <%= @produto.validade.strftime("%d/%m/%Y") %></p>
<p>Grupo: <%=h @produto.grupo.descricao %></p>
<p>Data do Cadastro: <%= @produto.created_at.strftime("%d/%m/%Y %H:%M") %></p>
</h4>

<p>
	<%= link_to 'Voltar', produtos_path %>
    <%= link_to 'Editar' , edit_produto_path %>
    <%= link_to 'Excluir', produto_path, method: :delete, data: { confirm: 'Você tem certeza que deseja apagar o produto?' } %>
</p>